GRANT EXECUTE ON SYS.DBMS_CRYPTO TO pdbAdmin;

CREATE USER Client_user IDENTIFIED BY password;
CREATE USER Admin_user IDENTIFIED BY password;



GRANT ALL PRIVILEGES TO pdbAdmin;
CREATE TABLESPACE users_tablespace
DATAFILE 'users_tablespace.dbf' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER USER pdbAdmin QUOTA UNLIMITED ON USERS_TABLESPACE;
ALTER USER Client_user QUOTA UNLIMITED ON USERS_TABLESPACE;
ALTER USER Admin_user QUOTA UNLIMITED ON USERS_TABLESPACE;
